Improve terms-gen, terms-gen-meta, derivers
Fundament-Software/Alicorn0 pull request #95
Opened 2024-08-10 11:04 UTC by AstroSnail

and fix types of things and fix mistakes that became visible.

this was intended to be part of a refactor to implement recursion schemes, but that's been put off so we just get this for now

2024-08-10 20:54 UTC, ErikMcClure requested changes

2024-08-10 20:54 UTC, ErikMcClure commented on derivers.lua
> +		error("can't derive eq for a foreign type")
these should say "can't derive eq()" for clarity. This applies to all "can't derive blah" statements in this file.

2024-08-11 07:04 UTC, ErikMcClure approved these changes
This seems fine from my perspective.

2024-08-11 23:58 UTC, aiverson approved these changes

2024-08-12 00:02 UTC, merged